#!/bin/bash


#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=messung2_2_2.out

srun ~/HPC/Blatt04/partdiff-seq 12 2 512 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 256 2 2 16384
