#!/bin/bash


#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=posix02-03.out

srun ~/HPC/Blatt05/pde/partdiff-posix 2 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 2 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 2 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 3 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 3 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 3 2 512 2 2 1024
