#!/bin/bash


#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=messung2_3_2.out

srun ~/HPC/Blatt04/partdiff-seq 12 2 128 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 64 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 32 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 16 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 8 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 4 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 2 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 12 2 1 2 2 16384
