#!/bin/bash


#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=3
#SBATCH --output=messung2.out

srun ~/HPC/Blatt04/partdiff-seq 1 2 1024 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 512 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 256 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 128 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 64 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 32 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 16 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 8 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 4 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 2 2 2 16384

echo --------------------------------------------

srun ~/HPC/Blatt04/partdiff-seq 1 2 1 2 2 16384
