#!/bin/bash


#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=posix01.out

srun ~/HPC/Blatt05/pde/partdiff-posix 1 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 1 2 512 2 2 1024
------------------------------------------------------------------------------
srun ~/HPC/Blatt05/pde/partdiff-posix 1 2 512 2 2 1024
